name: code-inspector-ben

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**/README.md'
      - '**/Commands.md'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  check-quality:
    runs-on: ubuntu-latest
    name: A job to check my code quality
    steps:
      - name: Check code meets quality standards
        id: code-inspector-ben
        uses: bensuperpc/code-inspector@v1.0.3
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          code_inspector_access_key: ${{ secrets.CODE_INSPECTOR_ACCESS_KEY }}
          code_inspector_secret_key: ${{ secrets.CODE_INSPECTOR_SECRET_KEY }}
          min_quality_grade: 'WARNING'
          min_quality_score: '98'
          max_defects_rate: '0.005'
          max_complex_functions_rate: '0.005'
          max_long_functions_rate: '0.005'
          project_name: ''
          max_timeout_sec: '600'
