name: "tagged-release"

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: "📥 Checkout Code"
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: "✅ Check bash syntax"
        run: sudo make check
      - name: "✅ Check dependency"
        run: sudo make check-dep
      - name: "🛠️ Install"
        run: sudo make install
      - name: "🛠️ update (optional)"
        run: sudo make update
      - name: "🧹 Uninstall"
        run: sudo make uninstall
      - name: "🛠️ build full package"
        run: sudo make dist-full
      - name: "🛠️ build package"
        run: sudo make dist
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE
            *.tar.xz
            *.sha384
